### ISSUE TITLE
Collection/autocomplete: throws 'No component factory found for KitOverlayHostWrapperComponent' error

### ISSUE THREAD

**Issue by erdkse** [ngx-kit/ngx-kit#237]
I just generated autocomplete module and attempted to use but after importing AutocompleteModule I get this error.

**Comment by navix** [comment]
Thanks for pointing the bug!

You can fix it by exporting `KitOverlayModule` from `AutocompleteModule`:
```
@NgModule({
  ...
  exports: [
    ...
    KitOverlayModule,
  ],
```

Or install updated collection `npm i @ngx-kit/collection` and re-generate the module.

Fixed in e6d7b04.
