### ISSUE TITLE
ui-autocomplete emit select bug

### ISSUE THREAD

**Issue by loopezz** [ngx-kit/ngx-kit#241]
The EventEmitter 'select' won't be triggered when selecting an option in at least Firefox and Safari. However, it does work on Chrome. Tested on an iMac.

This issue also occurs on https://ngx-kit.com/collection/module/ui-autocomplete. Therefor no further demo will be required.

**Comment by navix** [comment]
Hi! Thanks for using ngx-kit.

Can't reproduce the problem on windows.
Is model value changing on select?

I've just realize that `select` is a reserved word for native event. Update `@ngx-kit/collection` to 6.0.2, re-generate module and try again (`select` renamed to `optionSelect`). 

Anyway, not sure it will help, wait for your update.

**Comment by loopezz** [comment]
Model value doesn't change on select. I have created a list on tested browsers and OS.

Tested and works on:
- Chrome 68.0.3440.106 64-bit (MacOS 10.13.4)
- Chrome 68.0.3440.106 64-bit (Windows 10)
- FireFox 61.0.2 64-bit (Windows 10)
- Edge 42.17134.1.0 (Windows 10)
- Chrome (Android 6.0.1)

Tested and works not on:
- Firefox 61.0.2 64-bit (MacOS 10.13.4)
- Safari 11.1 (MacOS 10.13.4)
- IE 11 (Windows 10)
- Safari (iOS 11.4.1)

**Comment by navix** [comment]
Hey, check please this demo: http://oak.pw/navix/ngx-kit-ac-test/
It now works for me in IE11.

**Comment by loopezz** [comment]
That one works! :)

**Comment by navix** [comment]
Nice, I will publish new release today. 
That was an error with blur listener, great catch, thanks.

**Comment by loopezz** [comment]
Sorry, I edited my comment. I was a bit too fast with my feedback.

**Comment by navix** [comment]
I see. Could you please give me a console screenshot from the demo (after failed select)? http://oak.pw/navix/ngx-kit-ac-test/

**Comment by navix** [comment]
Let's try the next demo: http://oak.pw/navix/ngx-kit-ac-test-2/
It works okay for Safari 5.1.7 on Win.

**Comment by loopezz** [comment]
It also works on Safari (iOS 11.4.1) and Safari 11.1 (macOS 10.13.4) now. Thank you very much for the fast response!

**Comment by navix** [comment]
Thank you for the issue and help!

You can update core and collection to [6.1.0](https://github.com/ngx-kit/ngx-kit/releases/tag/6.1.0) and re-generate autocomplete module.
