### ISSUE TITLE
Help with Slider+HammerJs

### ISSUE THREAD

**Issue by philoliver** [ngx-kit/ngx-kit#246]
Hi,
I installed hammerJs via `npm i hammerjs --save` and then imported it in `main.ts` like so: `import 'hammerjs';`.

Unfortunately, the slider still doesn't react on mobile phone. I am not sure where to start looking for the mistake.

The project is in Angular6 and has multiple modules. I changed the style of the slider, but the .ts file is as originally generated.

Would be happy about any input. Thanks!

**Comment by navix** [comment]
Hi! Thanks for using ngx-kit.
Is default slider working on your mobile? https://ngx-kit.com/collection/module/ui-slider

**Comment by philoliver** [comment]
Hi Navix,
Thanks for your response. Yes, on the demo website works perfectly, but the generated one not. I guess I am not importing hammer.js correctly?

**Comment by philoliver** [comment]
Hi,

It is working now. My bad! I was not having the latest version of ngx-kit...
