### ISSUE TITLE
Using ui-loading-bar without other ngx-kit components produces an error.

### ISSUE THREAD

**Issue by luastoned** [ngx-kit/ngx-kit#247]
It seems like the generated `ui-loading-bar` module does not import/export `KitOverlayModule` which causes the following error:

`Unhandled Promise rejection: No component factory found for KitOverlayHostWrapperComponent. Did you add it to @NgModule.entryComponents? ; Zone: <root> ; Task: Promise.then ; Value: Error: "No component factory found for KitOverlayHostWrapperComponent. Did you add it to @NgModule.entryComponents?"`

**Comment by navix** [comment]
Thanks for the issue. Fixed in https://github.com/ngx-kit/ngx-kit/releases/tag/6.1.1
