### ISSUE TITLE
Using HMR injects overlays multiple times

### ISSUE THREAD

**Issue by luastoned** [ngx-kit/ngx-kit#249]
When using HMR (aka developing) the `<div class="kit-overlay-container">` tag gets injected on each hot reload.

Could the existence of this tag be checked and then not injected again?

**Comment by navix** [comment]
> Could the existence of this tag be checked and then not injected again?

Of course. Fix will be released soon with the next minor patch.

Thank for using ngx-kit!

**Comment by navix** [comment]
Fixed in (7.0.0)[https://github.com/ngx-kit/ngx-kit/releases/tag/7.0.0].
