### ISSUE TITLE
Can't update to Angular 7 due to typescript peer dependency

### ISSUE THREAD

**Issue by luastoned** [ngx-kit/ngx-kit#254]
When running `ng update @angular/cli @angular/core` the following error appears:

`Package "@ngx-kit/core" has an incompatible peer dependency to "typescript" (requires "~2.7.2", would install "3.1.3").`

**Comment by navix** [comment]
Ngx-kit with angular 7 and new typescript support and proper deps will be released soon.
But current version should be compatible, you can force the update:
```
ng update @angular/cli @angular/core --force
```

**Comment by navix** [comment]
Closed by [7.0.0 release](https://github.com/ngx-kit/ngx-kit/releases/tag/7.0.0).
