### ISSUE TITLE
Error after update to Angular 8

### ISSUE THREAD

**Issue by opterion** [ngx-kit/ngx-kit#333]
After updating to Angular 8 build fails with error: **ERROR in node_modules/@ngx-kit/core/src/kit-overlay/kit-overlay.service.d.ts(2,32): error TS2307: Cannot find module '@angular/core/src/di/provider'.**

It's caused by line `import { StaticProvider } from '@angular/core/src/di/provider';`
The reason is that `StaticProvider` type isn't exported anymore.

**Comment by JoostK** [comment]
For context please see https://github.com/angular/angular/issues/30734#issuecomment-497077346

**Comment by navix** [comment]
Thank for the report, will be fixed in a couple days.

**Comment by opterion** [comment]
Please, take a look at PR above. It should fix the problem.
Thanks in advance!

**Comment by navix** [comment]
@opterion Thanks a lot, seems only that import was a problem.

Path released in version `7.3.2`.

```
$ npm i @ngx-kit/core@latest
```

**Comment by opterion** [comment]
@navix Thanks a lot!
